version: '3.0'
services:

  rpe_frontend:
    build: ./frontend
    container_name: rpe_react_front
    ports:
      - '8081:8080'
      - '8082:8080'
      - '8083:8080'
      - '8084:8080'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    # in dev yarn dev1/2/3/4 with port and without run nginx
    command: ['yarn', 'start']
    env_file:
      - ./frontend/.env
    networks:
      - rpe_network
    stdin_open: true
    tty: true

  # rpe_backend:
  #   build: ./rails-api
  #   container_name: rpe_rails_back
  #   env_file:
  #     - ./rails-api/env/development/rpe_back_db
  #     - ./rails-api/env/development/rpe_backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./rails-api:/usr/src/app
  #   depends_on:
  #     - rpe_back_redis
  #     - rpe_back_db
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0'
  #   restart: unless-stopped
  #   networks:
  #     - rpe_network
  #   stdin_open: true
  #   tty: true

  # rpe_back_redis:
  #   image: redis:7.2
  #   container_name: rpe_back_redis
  #   command: redis-server
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/var/lib/docker/volumes/center-credit-module_redis_data/_data
  #   networks:
  #     - rpe_network

  # rpe_back_db:
  #   image: postgres:16.2
  #   container_name: rpe_back_db
  #   env_file:
  #     - ./rails-api/env/development/rpe_back_db
  #   volumes:
  #     - db_data:/var/lib/docker/volumes/center-credit-module_db_data/_data
  #   restart: unless-stopped
  #   networks:
  #     - rpe_network

  nginx:
    image: nginx:1.25.5-alpine
    container_name: rpe-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - rpe_frontend
      # - api
    networks:
      - rpe_network

# volumes:
#   db_data:
#   redis_data:

networks:
  rpe_network:
    driver: bridge
